"""Document models, persistence helpers, and template filling."""

from uplands_site_command_centre.permits.models import (
    BaseDocument,
    CarrierComplianceDocument,
    CarrierComplianceDocumentType,
    COSHHDocument,
    ComplianceAlertStatus,
    COMMON_CONSTRUCTION_EWC_CODES,
    DocumentStatus,
    FileGroup,
    IncidentLogDocument,
    IncidentType,
    InductionDocument,
    LadderInspectionRecord,
    LadderPermit,
    LadderStabilisationMethod,
    Permit,
    PermitDocument,
    RAMSDocument,
    SiteAttendanceRecord,
    SiteAttendanceRegister,
    TemplateRegistry,
    ValidationError,
    VerificationStatus,
    WasteRegister,
    WasteTransferNoteDocument,
)
from uplands_site_command_centre.permits.carrier_compliance import (
    CarrierComplianceFinding,
    check_carrier_compliance,
)
from uplands_site_command_centre.permits.repository import (
    DocumentNotFoundError,
    DocumentRepository,
    IndexedFileRecord,
    PermitNotFoundError,
    PermitRepository,
)
from uplands_site_command_centre.permits.ingestion_engine import IngestionEngine
from uplands_site_command_centre.permits.template_manager import (
    TemplateManager,
    TemplateValidationError,
)

__all__ = [
    "BaseDocument",
    "CarrierComplianceDocument",
    "CarrierComplianceDocumentType",
    "CarrierComplianceFinding",
    "ComplianceAlertStatus",
    "COSHHDocument",
    "check_carrier_compliance",
    "COMMON_CONSTRUCTION_EWC_CODES",
    "DocumentNotFoundError",
    "DocumentRepository",
    "DocumentStatus",
    "FileGroup",
    "IngestionEngine",
    "IndexedFileRecord",
    "IncidentLogDocument",
    "IncidentType",
    "InductionDocument",
    "LadderInspectionRecord",
    "LadderPermit",
    "LadderStabilisationMethod",
    "Permit",
    "PermitDocument",
    "PermitNotFoundError",
    "PermitRepository",
    "RAMSDocument",
    "SiteAttendanceRecord",
    "SiteAttendanceRegister",
    "TemplateRegistry",
    "TemplateManager",
    "TemplateValidationError",
    "ValidationError",
    "VerificationStatus",
    "WasteRegister",
    "WasteTransferNoteDocument",
]
